"""
NYC Guide — all place data (attractions + restaurants)
"""

# ── Tourist Attractions ───────────────────────────────────────────────────────
# (name, category, emoji, entry, tip, book_ahead)
ATTRACTIONS = {
    "Lower Manhattan": [
        ("9/11 Memorial & Museum",      "History",      "🏛️", "paid",  "Memorial pools are free; museum requires tickets. Arrive early — lines grow by 10am.", False),
        ("One World Observatory",       "Observation",  "🔭", "paid",  "Best clear-day views in the city. Buy tickets online to skip the queue.", True),
        ("The Oculus",                  "Architecture", "🕊️", "free", "Santiago Calatrava transit hub. Stunning at noon when sunlight hits the spine.", False),
        ("Battery Park",                "Attraction",   "🌿", "free", "Gateway to ferry terminals for Statue of Liberty & Staten Island. Great harbor views.", False),
        ("Statue of Liberty",           "Attraction",   "🗽", "paid",  "Reserve crown access months ahead. Pedestal is worth it if crown is sold out.", True),
        ("Ellis Island",                "Museum",       "🏛️", "paid",  "Included with Statue of Liberty ferry ticket. Allow 2–3 hours.", False),
        ("Governor's Island",           "Attraction",   "🏝️", "free", "Only open May–Oct. Free ferry from Battery Park. Rent a bike when you arrive.", False),
        ("Wall Street & Federal Hall",  "History",      "🏦", "free", "NYSE exterior + Federal Hall (free museum). Best on a weekday morning.", False),
        ("Staten Island Ferry",         "Attraction",   "⛴️", "free", "Completely free — best Statue of Liberty view in the city. 25-min ride.", False),
        ("National Museum of the American Indian", "Museum", "🏺", "free", "Underrated gem inside the stunning Alexander Hamilton Custom House.", False),
        ("St. Paul's Chapel",           "History",      "⛪", "free", "NYC's oldest surviving church (1766). Played a key role after 9/11.", False),
    ],
    "Midtown Manhattan": [
        ("Empire State Building",       "Observation",  "🏙️", "paid",  "Buy timed tickets online. Night visits are magical — less crowded after 9pm.", True),
        ("Top of the Rock",             "Observation",  "🔭", "paid",  "Better view of Empire State Building than from it. Sunset slot is the sweet spot.", True),
        ("Summit One Vanderbilt",       "Observation",  "🌆", "paid",  "Most immersive deck in the city — mirrors, glass floors, incredible 360° views.", True),
        ("Times Square",                "Attraction",   "✨", "free", "Best experienced at night. Skip the TKTS line if you booked shows in advance.", False),
        ("Rockefeller Center",          "Attraction",   "🏛️", "free", "The plaza is free. Ice rink in winter. NBC Studios tours available.", False),
        ("Radio City Music Hall",       "Attraction",   "🎭", "paid",  "Take the Stage Door Tour if you're not seeing a show — it's worth it.", False),
        ("NBC Studios Tour",            "Attraction",   "📺", "paid",  "Book ahead. Chance to see the Tonight Show or SNL sets.", True),
        ("St. Patrick's Cathedral",     "History",      "⛪", "free", "Free to enter. Stunning Gothic interior — visit on a weekday to avoid crowds.", False),
        ("Grand Central Terminal",      "History",      "🚂", "free", "Look up at the ceiling constellation. Free tours run on Wednesdays.", False),
        ("New York Public Library",     "History",      "📚", "free", "Step inside the Rose Main Reading Room — one of NYC's most beautiful interiors.", False),
        ("MoMA",                        "Museum",       "🎨", "paid",  "Free on Friday evenings 5:30–9pm. Picasso, Monet, Warhol — allow 2–3 hours.", False),
        ("Morgan Library & Museum",     "Museum",       "📜", "paid",  "Intimate and uncrowded. Rare manuscripts, Rembrandt drawings, a stunning library room.", False),
        ("Harry Potter Store",          "Store",        "🧙", "free", "World's largest Harry Potter store. No entry fee — budget for impulse buys.", False),
        ("FAO Schwarz",                 "Store",        "🪀", "free", "Iconic toy store. The giant piano floor is still there.", False),
        ("Fifth Avenue Luxury Stores",  "Store",        "🛍️", "free", "Gucci, Prada, Saks — window shopping is free. Peak crowds on weekends.", False),
        ("Museum of Broadway",          "Museum",       "🎭", "paid",  "Opened 2022. Great for theatre fans — interactive timeline of Broadway history.", False),
    ],
    "Chelsea & Hudson Yards": [
        ("The High Line",               "Attraction",   "🌿", "free", "Elevated park on a former rail line. Enter at Gansevoort or 34th St. Best in spring.", False),
        ("The Vessel",                  "Attraction",   "🐚", "free", "Climbable honeycomb sculpture. Free timed tickets required — book online.", True),
        ("Chelsea Market",              "Attraction",   "🥗", "free", "Food hall inside the old Nabisco factory. Los Tacos No. 1 is a must.", False),
    ],
    "Greenwich Village & SoHo": [
        ("Washington Square Park",      "History",      "🏛️", "free", "The arch is iconic. Lively on weekends — chess players, musicians, NYU students.", False),
        ("The Evolution Store",         "Store",        "🦕", "free", "Natural history curiosities — fossils, taxidermy, minerals. Fascinating browse.", False),
    ],
    "Flatiron & Gramercy": [
        ("Flatiron Building",           "History",      "🏢", "free", "Best photographed from the pedestrian island at 23rd & Broadway.", False),
        ("Madison Square Park",         "Attraction",   "🌳", "free", "Relax in the park then grab a Shake Shack burger — the original location.", False),
    ],
    "Upper East Side": [
        ("The Met",                     "Museum",       "🏛️", "paid",  "Pay-what-you-wish for NY state residents. Budget 3–4 hours minimum. Don't miss the rooftop.", False),
        ("Guggenheim Museum",           "Museum",       "🌀", "paid",  "The building IS the art. Frank Lloyd Wright spiral. Go on a Saturday evening.", False),
        ("Central Park",                "Attraction",   "🌳", "free", "Enter at 72nd St (Bethesda Fountain) or 59th St. Rent a bike to cover more ground.", False),
        ("Central Park Zoo",            "Zoo",          "🐧", "paid",  "Small but great for a quick visit. Snow leopards + penguin feeding time.", False),
    ],
    "Upper West Side": [
        ("American Museum of Natural History", "Museum", "🦕", "paid", "Pay-what-you-wish. The blue whale hall and dinosaur floors are unmissable.", False),
    ],
    "Brooklyn": [
        ("Dumbo",                       "Attraction",   "📸", "free", "Best Manhattan Bridge framing: Washington St between Water & Front.", False),
        ("Jane's Carousel",             "Attraction",   "🎠", "paid",  "Restored 1922 carousel in a glass pavilion. $2 a ride — a genuine NYC gem.", False),
        ("Brooklyn Bridge Park",        "Attraction",   "🌉", "free", "1.3 miles of waterfront. Best Manhattan skyline views at sunset.", False),
        ("Brooklyn Bridge",             "History",      "🌉", "free", "Walk it from the Manhattan side. Takes ~30 min. Go early to beat crowds.", False),
        ("Brooklyn Heights Promenade",  "Attraction",   "🌆", "free", "The classic NYC skyline view. Perfect at golden hour.", False),
        ("Domino Park",                 "Attraction",   "🌿", "free", "Former Domino Sugar factory turned park on the Williamsburg waterfront.", False),
        ("Brooklyn Museum",             "Museum",       "🏛️", "paid",  "Vast collection, rarely overcrowded. First Saturdays (monthly) are free + lively.", False),
        ("Prospect Park",               "Attraction",   "🌳", "free", "Brooklyn's answer to Central Park. Less crowded, more local.", False),
        ("NYC Transit Museum",          "Museum",       "🚇", "paid",  "Inside a real decommissioned subway station. Kids and adults both love it.", False),
        ("Coney Island",                "Attraction",   "🎡", "free", "Best May–Sep. Luna Park rides are paid. The boardwalk and beach are free.", False),
    ],
    "The Bronx": [
        ("Bronx Zoo",                   "Zoo",          "🦁", "paid",  "One of the world's largest zoos. Wednesdays are pay-what-you-wish. Budget a full day.", False),
    ],
    "Queens": [
        ("Queens Museum",               "Museum",       "🏛️", "paid",  "Home to the famous Panorama of NYC — a scale model of every city building.", False),
    ],
    "Staten Island": [
        ("Fort Wadsworth",              "History",      "🏰", "free", "Free entry. Stunning views of the Verrazano Bridge and Lower Bay.", False),
        ("National Lighthouse Museum",  "Museum",       "🔦", "paid",  "Near the St. George Ferry Terminal. Unique and undervisited.", False),
    ],
    "Roosevelt Island": [
        ("Four Freedoms Park",          "History",      "🕊️", "free", "FDR memorial at the southern tip. Serene and almost always quiet.", False),
        ("Renwick Ruins",               "History",      "🏚️", "free", "Atmospheric ruins of a 19th-century smallpox hospital.", False),
    ],
}

# ── Restaurants & Bars ────────────────────────────────────────────────────────
# (name, cuisine, price, tip)
RESTAURANTS = {
    "Lower Manhattan & Tribeca": [
        ("Bubby's",             "American",         "$$",   "Classic Tribeca brunch spot. Famous for pies and comfort food. Long weekend waits."),
        ("The Wooly",           "Bar",              "$",    "Cozy bar near the Woolworth Building. Good cocktails, great after work."),
        ("The Corner Store",    "American",         "$$$",  "Elegant Tribeca bistro. Great for a special lunch in a beautiful room."),
    ],
    "Chinatown & Lower East Side": [
        ("Russ & Daughters Cafe",           "Jewish Deli",      "$$",   "LES institution since 1914. Best bagel with lox in the city. Expect a wait on weekends.", "sfp"),
        ("Ice and Vice",                    "Desserts",         "$",    "Phil Rosenthal's ice cream obsession. Wild flavours: peach jalapeño, yuzu coconut milk. Open late.", "sfp"),
        ("Attaboy",                         "Cocktail Bar",     "$$",   "No-menu speakeasy — tell the bartender what you feel like. Hidden door, incredible drinks."),
        ("The Back Room",                   "Cocktail Bar",     "$",    "Actual Prohibition-era speakeasy. Enter through a side alley. Drinks served in teacups."),
        ("Dhamaka",                         "Indian",           "$$",   "Bold, unapologetic regional Indian cooking. Not your average curry house. Book ahead."),
        ("Davelle",                         "Japanese",         "$",    "Tiny Japanese coffee and sweets shop. Exquisite matcha drinks and small bites."),
        ("Van Đa",                          "Vietnamese",       "$$",   "Modern Vietnamese in a beautiful space. The banh mi and pho are exceptional."),
        ("Ivan Ramen",                      "Ramen",            "$$",   "New York's finest ramen. Jewish-American chef, Japanese obsession. The shio ramen is perfect."),
        ("Clinton St. Baking Company",      "American",         "$$",   "Best pancakes in NYC (blueberry or maple butter). Weekend waits can hit 2 hours — go weekday."),
        ("Beauty & Essex",                  "American",         "$$$",  "Hidden behind a pawnshop. Glamorous space, great cocktails, American small plates."),
        ("Jajaja Mexicana",                 "Vegan Mexican",    "$",    "All-vegan Mexican — you won't miss the meat. Great margaritas too."),
        ("Morgenstern's Finest Ice Cream",  "Desserts",         "$",    "Unusual flavors (black sesame, miso cherry). Small shop, big lines in summer."),
        ("Supermoon Bakehouse",             "Bakery",           "$",    "Instagram-famous croissants and pastries. Limited daily batches — go early."),
        ("Casa Adela",                      "Puerto Rican",     "$",    "No-frills LES institution. Best pernil and rice and beans in the city."),
        ("Sun Hing Lung",                   "Chinese",          "$",    "Authentic Cantonese grocery/deli in Chinatown. Great BBQ pork buns."),
        ("Taiyaki NYC",                     "Japanese",         "$",    "Fish-shaped waffle cones with soft serve. Classic Chinatown queue spot."),
        ("Dim Sum Palace",                  "Chinese",          "$$",   "Solid dim sum, open late. Great after a show or night out."),
        ("Whiskey Tavern",                  "Bar",              "$",    "No-frills dive bar near Chinatown. Cheap drinks, good jukebox."),
        ("Pusu 璞素",                        "Chinese Veg.",     "$$",   "Elegant Chinese vegetarian cooking. One of the city's best kept secrets."),
        ("LOLITA",                          "Mexican",          "$",    "Buzzy LES taqueria. Great tacos and frozen margaritas at a fair price."),
        ("Superbueno",                      "Mexican",          "$$",   "Creative upscale Mexican. Excellent cocktail program. Book ahead."),
        ("Speedy Romeo",                    "Pizza",            "$$",   "Wood-fired pizza with creative toppings. The St. Louie white pizza is a revelation."),
    ],
    "East Village": [
        ("Caravan Of Dreams",       "Vegan",            "$",    "Long-running vegan institution. Comfort food done right without meat or dairy."),
        ("HAGS",                    "American",         "$$$",  "Queer-owned tasting menu. Inventive, soulful cooking. One of NYC's best new spots."),
        ("Baar Baar",               "Indian",           "$$",   "Modern Indian with a great cocktail bar. Excellent chaat and street food."),
        ("Cathédrale Restaurant",   "French Med.",      "$$$",  "Stunning space inside the Bowery Hotel. Elevated French-Mediterranean cooking."),
        ("Empellon Al Pastor",      "Mexican",          "$$",   "Alex Stupak's casual Mexican. Al pastor tacos are some of the best in the city."),
        ("The Black Ant",           "Mexican",          "$$",   "Creative Mexican with unusual ingredients (crickets, ant salt). Worth the adventure."),
        ("The Summit Bar",          "Bar",              "$",    "Beloved EV dive bar. Cheap drinks, no attitude, great jukebox."),
        ("Doc Holliday's",          "Bar",              "$",    "Classic EV dive bar. Country music, cheap beers. A genuine NYC institution."),
        ("Ray's Candy Store",       "Desserts",         "$",    "24/7 candy/snack store run by Ray himself. EV landmark. Get the Belgian waffles."),
        ("Lips Cafe",               "American",         "$$",   "Iconic drag restaurant. Dinner with a show — book for birthdays/bachelorettes."),
        ("Ix",                      "Mayan",            "$$$",  "Rare Mayan cuisine — an NYC original. Intricate, smoke-forward cooking."),
        ("Claud",                   "French American",  "$$$",  "Acclaimed wine bar-restaurant. Natural wine, French-leaning small plates. Hard to book."),
        ("Formosa",                 "Taiwanese",        "$$",   "Creative Taiwanese cooking. The scallion pancakes and braised pork rice are outstanding."),
        ("Apartment 5",             "Bar",              "$",    "Laid-back EV bar. Good natural wine selection and a relaxed local crowd."),
        ("Cellar Dog",              "American",         "$",    "Hot dogs, cold beer, no pretense. Late-night EV staple."),
        ("Mermaid Mexicana",        "Mexican Seafood",  "$$",   "Mexican-seafood hybrid. Ceviche and fish tacos in a lively room."),
        ("Sentir Vegan Mexican",    "Vegan Mexican",    "$",    "Vegan Mexican comfort food. Great burritos and enchiladas at honest prices."),
    ],
    "NoLIta, NoHo & SoHo": [
        ("La Mercerie",         "French",           "$$$",  "Elegant French café inside Roman & Williams Guild. Perfect croissants and steak frites in a stunning room."),
        ("Raoul's",             "French",           "$$$",  "Legendary SoHo bistro since 1975. Dark, romantic, great steak au poivre. Reservations essential."),
        ("Balthazar",           "French Brasserie", "$$$",  "The SoHo institution. Best for brunch or late night. Steak frites, oysters, the works."),
        ("Eileen's Special Cheesecake", "Bakery",   "$",    "NYC's finest cheesecake since 1974. Tiny NoLIta shop. Mini cheesecakes to go."),
        ("Jack's Wife Freda",   "Mediterranean",    "$$",   "South African-Med brunch staple. The green shakshuka is iconic. Multiple locations."),
        ("La Esquina Brasserie","Mexican",           "$$",   "Subterranean brasserie hidden below a taqueria. Great margaritas, festive atmosphere."),
        ("Emilio's Ballato",    "Italian",          "$$",   "Cash-only red-sauce Italian since 1956. Everyone from Mick Jagger to Obama has eaten here."),
        ("Thai Diner",          "Thai",             "$$",   "Andy Ricker's Thai-American comfort food. The pad see ew pancake is wild and good."),
        ("Little Prince",       "French",           "$$",   "Charming SoHo French bistro. Perfect steak frites and terrific natural wine list."),
        ("ATLA",                "Mexican",          "$$",   "Enrique Olvera's casual Mexican. Great for lunch or a long boozy brunch."),
        ("Maman",               "French Bakery",    "$",    "Best butter croissant in NYC. Multiple locations — the SoHo one is a favourite."),
        ("A.R.T. SoHo",         "Rooftop Bar",      "$$",   "Arlo Hotel rooftop. Great views, cocktails, casual food. Best in summer."),
        ("Sartiano's",          "Italian",          "$$$",  "Celebrity-packed Italian in SoHo. The pasta is excellent but the scene is the main attraction."),
        ("Temple Bar",          "Cocktail Bar",     "$$",   "Moody NoHo cocktail bar. Plush booths, strong drinks. One of the best bars in the city."),
        ("Lafayette Grand Café","French",           "$$",   "Massive French brasserie in NoHo. Incredible pastry counter, good prix-fixe brunch."),
        ("Mother's Ruin",       "Bar",              "$",    "Friendly NoLIta bar. Great cocktails at reasonable prices, lively crowd."),
        ("Tacombi",             "Mexican",          "$",    "Breezy taqueria with multiple NYC locations. The NoLIta original is the best."),
        ("Torrisi",             "Italian",          "$$$",  "Major NYC restaurant. Italian-American cooking at its most creative. Book far ahead."),
        ("Le Botaniste",        "Vegan",            "$$",   "Belgian organic vegan chain. Beautiful presentations, excellent daily specials."),
        ("Bittersweet",         "Desserts",         "$",    "French-inspired pastry shop. Excellent tarts, cakes, and afternoon tea."),
    ],
    "West Village & Greenwich Village": [
        ("Waverly Inn",         "American",         "$$$",  "Cozy celebrity haunt. Classic American comfort food. Reservations hard to get — try for lunch."),
        ("Via Carota",          "Italian",          "$$$",  "No reservations. Best cacio e pepe in NYC. Arrive right at opening or expect 1hr+ wait."),
        ("L'Artusi",            "Italian",          "$$$",  "Excellent West Village Italian. Great pasta and wine list. Book well ahead."),
        ("Carnitas Ramirez",    "Mexican",          "$",    "Best carnitas in NYC. Simple counter spot — get tacos and a beer and enjoy."),
        ("Market Table",        "American",         "$$$",  "Lovely neighbourhood American. Seasonal menu, warm room. Great for a date."),
        ("I Sodi",              "Italian",          "$$$",  "Intimate Tuscan cooking. The ribollita and handmade pasta are outstanding."),
        ("Don Angie",           "Italian",          "$$$",  "Creative Italian-American. The pinwheel lasagna is the dish of the decade. Book far ahead."),
        ("Bleecker Street Pizza","Pizza",           "$",    "Classic NYC slice. The Nonna Maria white pie is the must-order."),
        ("Boucherie West Village","French",         "$$$",  "Parisian brasserie energy in the West Village. Great steak, excellent frites."),
        ("OLIO E PIÙ",          "Italian Pizza",    "$$",   "Wood-fired Neapolitan pizza in a beautiful West Village space."),
        ("L'industrie Pizzeria","Pizza",            "$",    "Arguably the best slice in NYC. The burrata and pesto slice is extraordinary. Always a line."),
        ("One if by Land, Two if by Sea", "American","$$$$","Most romantic restaurant in NYC. Former carriage house, live piano, prix-fixe. Special occasions only."),
        ("Dante West Village",  "Italian Bar",      "$$",   "Aperitivo bar vibes. Excellent Negroni, great cicchetti."),
        ("Employees Only",      "Cocktail Bar",     "$$",   "Best cocktail bar in NYC. Former speakeasy, kitchen open until 3:30am."),
        ("Comedy Cellar",       "Entertainment",    "$$",   "NYC's most famous comedy club. Unannounced drop-ins from the biggest names. Book early."),
        ("Bagel Bob's",         "Deli",             "$",    "Cheap, classic NYC bagels near NYU. No frills, pure utility."),
        ("Dante NYC",           "Italian Bar",      "$$",   "World's best bar (2019). Classic Negroni and aperitivo. Sit outside in summer."),
        ("The Golden Swan",     "Bar",              "$",    "Laid-back West Village bar. Great natural wine and a relaxed local crowd."),
        ("Jean's",              "American",         "$$$",  "Intimate West Village newcomer. Creative seasonal American cooking. Very hard to book."),
        ("LORE",                "American",         "$$$",  "Elegant West Village tasting menu. One of the most exciting newer openings."),
        ("El Mitote",           "Mexican",          "$$",   "Casual Mexican in the West Village. Great weekday lunch spot."),
        ("Carbone New York",    "Italian",          "$$$$", "The most famous table in NYC. Classic Italian-American. Book months ahead. The rigatoni vodka is legendary."),
        ("Semma",               "South Indian",     "$$$",  "Unapologetic South Indian cooking. The dosas and biryani are transcendent. Very hard to book."),
        ("Chinato",             "Wine Bar",         "$$",   "West Village wine bar with a strong Italian focus. Good aperitivo and small bites."),
        ("The Franklin Wine Bar","Wine Bar",        "$$",   "Neighbourhood wine bar with a well-curated list. Perfect for a low-key evening."),
    ],
    "Chelsea & Meatpacking": [
        ("Frying Pan NYC",      "Bar",              "$",    "Decommissioned lightship turned outdoor bar on the Hudson. Amazing in summer. Cash only."),
        ("Pastis",              "French Brasserie", "$$$",  "Meatpacking classic. Brunch is the main event — steak frites, croque madame, great people-watching."),
        ("Cull & Pistol",       "Seafood",          "$$$",  "Best oyster bar in NYC, inside Chelsea Market. Order the clam chowder and a dozen oysters."),
        ("Chama Mama",          "Georgian",         "$$",   "Chelsea's Georgian restaurant — khachapuri cheese bread is unmissable. Friendly and affordable."),
        ("Cookshop",            "American",         "$$$",  "Chelsea institution. Best for brunch — the eggs and cocktails are exceptional."),
        ("Cucina Alba",         "Italian",          "$$$",  "Hudson Yards Italian. Beautiful space, excellent pasta. Good for a business lunch."),
        ("Ci Siamo",            "Italian",          "$$$",  "Danny Meyer's Italian near Hudson Yards. Wood-fired cooking, handmade pasta, excellent service."),
        ("Kyma Hudson Yards",   "Greek",            "$$$",  "Upscale Greek seafood at Hudson Yards. Great grilled whole fish and mezze spread."),
    ],
    "Flatiron, NoMad & Gramercy": [
        ("Gramercy Tavern",     "American",         "$$$",  "One of NYC's great restaurants. The tavern room (no reservations) is great for a casual lunch."),
        ("Atoboy",              "Korean",           "$$",   "Creative Korean small plates. One of the best-value tasting menus in the city."),
        ("abcV",                "Vegetarian",       "$$$",  "Jean-Georges's vegetarian restaurant. Worth it even for meat eaters."),
        ("Oiji Mi",             "Korean",           "$$$",  "Upscale modern Korean. Beautiful banchan and inventive mains. Reservations essential."),
        ("Sunflower Gramercy",  "Indian Veg.",      "$$",   "Lovely Indian vegetarian spot. Great thali and weekend brunch."),
        ("Cosme",               "Mexican",          "$$$",  "Enrique Olvera's fine-dining Mexican. The corn husk meringue dessert is legendary."),
        ("Eleven Madison Park", "American",         "$$$$", "One of the best restaurants in the world. Plant-based tasting menu. Special occasion territory."),
        ("ILILI",               "Lebanese",         "$$$",  "Lively Lebanese in NoMad. Great mezze spread — hummus, kibbeh, fattoush."),
        ("Terroir",             "Wine Bar",         "$$",   "Natural wine bar. No-frills, expert selection, excellent for a late-evening glass."),
        ("Lola Taverna",        "Greek",            "$$",   "Vibrant Greek taverna near Flatiron. Great spreads, grilled meats, good ouzo selection."),
        ("ACRU",                "American",         "$$$",  "Refined NoMad American. Seasonal tasting menu, excellent cocktail program."),
        ("Osteria Delbianco",   "Italian",          "$$$",  "Elegant Flatiron Italian. Northern Italian cooking with an excellent wine list."),
    ],
    "Midtown Manhattan": [
        ("The Modern",          "French American",  "$$$$", "MoMA's two-Michelin-star restaurant. The bar room is more affordable and equally excellent."),
        ("Koloman",             "Austrian",         "$$$",  "Hotel Ace Austrian restaurant. The schnitzel is the best in NYC. Buzzy but not too loud."),
        ("L'Avenue at Saks",    "French",           "$$$",  "Rooftop at Saks Fifth Avenue. Great for lunch with views of St Patrick's Cathedral."),
        ("SEOUL SALON NYC",     "Korean",           "$$",   "Modern Korean in Koreatown. Great fried chicken and creative cocktails."),
        ("NARO",                "Korean",           "$$$",  "Refined Korean tasting menu in Koreatown. Exceptional value for the quality."),
        ("ATOMIX",              "Korean",           "$$$$", "Two Michelin stars. The most technically impressive Korean restaurant in the US. Book months ahead."),
        ("Le Bernardin",        "French Seafood",   "$$$$", "Three Michelin stars. The best seafood restaurant in America. Full tasting menu or à la carte."),
        ("Cho Dang Gol",        "Korean",           "$$",   "Koreatown institution known for homemade tofu. Sundubu jjigae is the must-order."),
        ("Joomak Banjum",       "Korean",           "$$$",  "Creative upscale Korean in Koreatown. Beautiful presentations, excellent cocktails."),
        ("The Polo Bar",        "American",         "$$$",  "Ralph Lauren's restaurant under the flagship store. Classic American supper club vibes."),
        ("Gaonnuri",            "Korean BBQ",       "$$",   "Sky-high Korean BBQ with Manhattan views. Solid KBBQ at a fair price for Midtown."),
        ("Patent Pending",      "Cocktail Bar",     "$$",   "Speakeasy-style bar in Hotel Henri. Excellent mixology, moody atmosphere."),
        ("Nobu Fifty Seven",    "Japanese",         "$$$$", "The Midtown Nobu. Black cod miso is mandatory. Still worth it after all these years."),
        ("Little Alley",        "Chinese",          "$$",   "Authentic Sichuan cooking in Midtown. Great cold noodles and mapo tofu."),
        ("Danji",               "Korean",           "$$",   "Hell's Kitchen Korean. Pork belly ssam and crispy squid are highlights."),
        ("Le Rock",             "French Brasserie", "$$$",  "Elegant French brasserie at Rockefeller Center. The beef tartare and tarte tatin are excellent."),
        ("Hangawi",             "Korean Veg.",      "$$",   "Floor-seating Korean vegetarian. Meditative atmosphere, exquisite tofu and mountain vegetable dishes."),
        ("The Rum House",       "Bar",              "$$",   "Intimate Midtown piano bar. Caribbean-leaning cocktails, live music most nights."),
        ("Jazba",               "Pakistani",        "$$",   "Excellent Pakistani cooking in Midtown. The karahi and nihari are exceptional."),
        ("Maison Close",        "French",           "$$$",  "Intimate French restaurant in Murray Hill. Classic cooking done with care."),
        ("Chambers",            "American",         "$$",   "Reliable Midtown American brasserie. Good for a business lunch."),
        ("Ayza Wine & Chocolate","Wine Bar",        "$$",   "Midtown wine bar with a chocolate pairing menu. Great for a date night."),
        ("Sogno Toscano",       "Italian",          "$$$",  "Tuscan market and restaurant in Midtown. Quality imported Italian products plus solid cooking."),
        ("SUKH",                "Indian",           "$$$",  "Refined Indian cooking in a calm Midtown setting. Excellent tasting menu."),
    ],
    "Upper West Side": [
        ("Bar Boulud",          "French",           "$$$",  "Daniel Boulud's UWS brasserie. Best for the charcuterie board and the burger at lunch."),
        ("Barney Greengrass",   "Jewish Deli",      "$$",   "The Sturgeon King since 1908. Weekend brunch lines are long but worth it. Get scrambled eggs with lox."),
        ("Cafe Luxembourg",     "French",           "$$$",  "Classic UWS bistro since 1983. Excellent steak frites, great people-watching."),
        ("Tatiana by Kwame Onwuachi", "Caribbean",  "$$$",  "James Beard Award winner. Stunning West African and Caribbean cooking near Lincoln Center."),
        ("Levain Bakery",       "Bakery",           "$",    "The iconic 6oz chocolate chip walnut cookie. Worth every calorie. Multiple locations."),
        ("The Franklin Wine Bar","Wine Bar",        "$$",   "UWS neighbourhood wine bar. Well-curated list, cosy room."),
    ],
    "Upper East Side": [
        ("Kappo Masa",          "Japanese",         "$$$$", "Larry Gagosian's omakase. Exceptional sushi, exceptional prices."),
        ("Le Veau d'Or",        "French",           "$$$",  "Revived 1930s French bistro. Time-capsule décor, perfect classic cooking."),
        ("Theodora",            "American Med.",     "$$$",  "Chic UES newcomer with Mediterranean-leaning cooking. Great natural wine list."),
    ],
    "Harlem & Upper Manhattan": [
        ("Beatstro",            "American",         "$$",   "Harlem supper club with live music and soul food. Great for a special evening."),
        ("Taco Mix",            "Mexican",          "$",    "East Harlem taqueria institution. Outstanding al pastor tacos, always a local crowd."),
        ("Oso",                 "Mexican",          "$$",   "Washington Heights Mexican. Inventive cooking and an excellent mezcal selection."),
        ("Ginjan Cafe",         "West African",     "$",    "Harlem café serving West African teas, smoothies, and snacks. A neighbourhood gem."),
    ],
    "Williamsburg & Greenpoint": [
        ("Peter Luger Steak House", "American",     "$$$$", "Cash-only legendary steakhouse since 1887. Order the porterhouse for two. Reservations essential.", "sfp"),
        ("GERTIE",              "American Jewish",  "$$",   "Nostalgic Jewish-American diner vibes. The chopped cheese and egg cream are iconic."),
        ("Cafe Kestrel",        "American",         "$$",   "Williamsburg neighbourhood café with excellent coffee and seasonal food."),
        ("McCarren Parkhouse",  "American",         "$$",   "Great park-adjacent bar and restaurant near McCarren Park. Good burgers."),
        ("Corima",              "Mexican",          "$$$",  "Acclaimed Mexican tasting menu. One of Brooklyn's best restaurants. Book well ahead."),
        ("Cafe Colette",        "French",           "$$",   "French café in Williamsburg. Wonderful for weekend brunch with a croissant and coffee."),
        ("Qahwah House Coffee", "Yemeni Coffee",    "$",    "Yemeni coffee ritual. Incredible spiced coffee in a welcoming space."),
        ("Sunday In Brooklyn",  "American Brunch",  "$$",   "One of NYC's best brunches. The malted pancakes are legendary. Long weekend waits."),
        ("Ainslie",             "American",         "$$",   "Laid-back Williamsburg bar with excellent food. Great for a casual weeknight dinner."),
        ("Westlight",           "Rooftop Bar",      "$$",   "William Vale Hotel rooftop. 360° Brooklyn and Manhattan views. Best at sunset."),
        ("Llama Inn",           "Peruvian",         "$$$",  "Outstanding modern Peruvian. The ceviche and causa are standouts. Book ahead."),
        ("Mesa Coyoacan",       "Mexican",          "$$",   "Regional Mexican in Williamsburg. The mole negro is outstanding."),
        ("The Four Horsemen",   "Wine Bar",         "$$$",  "James Murphy's (LCD Soundsystem) natural wine bar. Exceptional wine list, excellent food."),
        ("DSK Brooklyn",        "Bar",              "$",    "No-frills Williamsburg bar. Good beer selection, welcoming crowd."),
        ("Milly's Neighborhood Bar", "Bar",         "$",    "Chill Williamsburg neighbourhood bar. Good cocktails, low-key atmosphere."),
        ("Sip&Guzzle",          "Bar",              "$",    "Laid-back bar in Williamsburg. Great for a casual drink after exploring the neighbourhood."),
        ("Santo Taco",          "Mexican",          "$",    "Counter-service tacos in Williamsburg. Fresh, fast, and very good."),
        ("Runner Up",           "Bar",              "$",    "Neighbourhood bar with a strong local following. Good cocktails and low-key energy."),
        ("Butler Bakeshop",     "Bakery",           "$",    "Williamsburg bakery with outstanding pastries and coffee. The kouign-amann is a must."),
        ("Bernie's",            "American",         "$$",   "Relaxed Greenpoint neighbourhood spot. Great for brunch or a casual dinner."),
        ("Oxomoco",             "Mexican",          "$$",   "Wood-fired modern Mexican in Greenpoint. The tlayuda is unmissable. Book for weekends."),
        ("Stoned Pizza",        "Pizza",            "$",    "Greenpoint pizza spot with creative toppings and a good by-the-slice selection."),
    ],
    "Fort Greene, Clinton Hill & Bed-Stuy": [
        ("Colonia Verde",       "Latin American",   "$$",   "Excellent Latin American in Fort Greene. Great cocktails and brunch."),
        ("Sisters",             "American Brunch",  "$$",   "Laid-back Fort Greene brunch spot. Excellent eggs and coffee. Long weekend waits."),
        ("LaRina Pastificio",   "Italian",          "$$",   "Handmade pasta and natural wine in Fort Greene. One of Brooklyn's best Italian spots."),
        ("Roman's",             "Italian",          "$$$",  "Beloved Fort Greene Italian. Seasonal, ingredient-driven, one of the best in Brooklyn."),
        ("Olea",                "Mediterranean",    "$$",   "Fort Greene Mediterranean. Good mezze and grilled fish in a warm space."),
        ("Miss Ada",            "Israeli Med.",     "$$$",  "Israeli-inspired cooking. Charred eggplant, tahini, amazing spreads. One of Brooklyn's best."),
        ("Walter's",            "American",         "$$",   "Fort Greene neighbourhood bar and restaurant. Great burgers and Sunday brunch."),
        ("Dept. of Culture",    "West African",     "$$",   "Bed-Stuy Nigerian-American restaurant. Jollof rice and suya skewers. Exciting and underrated."),
        ("Saraghina Caffè",     "Italian",          "$",    "Bed-Stuy neighbourhood Italian café. Great coffee, pastries, and casual lunch."),
        ("Place des Fêtes",     "French",           "$$$",  "Crown Heights French bistro. One of Brooklyn's most acclaimed restaurants. Book early."),
        ("Coffee Project NY",   "Café",             "$",    "Fort Greene specialty coffee shop. Excellent single origin brews and light bites."),
        ("Luanne's Wild Ginger","Asian Fusion",     "$$",   "Fort Greene Asian fusion. Creative dishes in a warm neighbourhood setting."),
        ("Gage & Tollner",      "American",         "$$$",  "Revived 1879 Downtown Brooklyn chophouse. Clams casino, dry-aged beef, classic cocktails."),
        ("Fan Fan Doughnuts",   "Bakery",           "$",    "Crown Heights doughnut shop. Creative flavours, excellent pastry technique. Go early."),
        ("Clover Hill",         "American",         "$$$",  "Brooklyn Heights neighbourhood gem. Small seasonal menu, excellent cocktails."),
    ],
    "Dumbo & Brooklyn Waterfront": [
        ("GRAN ELÉCTRICA",      "Mexican",          "$$",   "Dumbo Mexican with Brooklyn Bridge views. Great margaritas and tacos al pastor."),
        ("Cecconi's Dumbo",     "Italian",          "$$$",  "Glamorous waterfront Italian. Great for a special occasion with a view."),
        ("The River Café",      "American",         "$$$$", "Iconic restaurant under the Brooklyn Bridge. Best views in the city. Special occasions only."),
        ("Fornino Pier 6",      "Pizza",            "$$",   "Wood-fired pizza in Brooklyn Bridge Park. Perfect for outdoor dining in summer."),
        ("Time Out Market",     "Food Hall",        "$$",   "Brooklyn's best chefs under one roof. Great harbour views from the Dumbo food hall."),
    ],
    "Carroll Gardens, Cobble Hill & Boerum Hill": [
        ("Rucola",              "Italian",          "$$$",  "Boerum Hill Italian. Rustic, seasonal cooking. The pasta and natural wine list are top-notch."),
        ("Sailor",              "American",         "$$$",  "Carroll Gardens small plates. One of Brooklyn's best restaurants. Compact menu, big flavours."),
        ("Lucali",              "Pizza",            "$$",   "Arguably the best pizza in NYC. Cash only, BYOB. Put your name in at 5pm or wait 2–3 hours."),
        ("Claro",               "Mexican",          "$$$",  "Oaxacan cuisine in Gowanus. Exceptional mole, mezcal, and handmade tortillas."),
    ],
    "Prospect Heights & Park Slope": [
        ("Olmsted",             "American",         "$$$",  "Prospect Heights gem with a backyard garden. One of Brooklyn's most celebrated restaurants."),
        ("Evelina",             "Italian",          "$$",   "Prospect Heights Italian. Excellent pasta and a lovely, unfussy room."),
        ("Colonia Verde",       "Latin American",   "$$",   "Fort Greene–Prospect Heights border. Great cocktails and brunch."),
    ],
    "Bushwick": [
        ("Blanca",              "Italian",          "$$$$", "Carlo Mirarchi's tasting menu in Bushwick. One of NYC's most challenging and rewarding meals."),
        ("Rhodora Wine Bar",    "Wine Bar",         "$$",   "Natural wine bar in Bushwick. Low-key, knowledgeable staff, excellent pours."),
        ("PPL",                 "Bar",              "$",    "Bushwick bar with a strong local following. Good cocktails and live music some nights."),
        ("Bearded Lady",        "Bar",              "$",    "Bed-Stuy neighbourhood bar. Welcoming crowd, good cheap drinks."),
    ],
    "South & Downtown Brooklyn": [
        ("Randazzo's Clam Bar", "Seafood",          "$$",   "Sheepshead Bay institution since 1923. Best fried clams in the city. Very local crowd."),
        ("Brooklyn Sweet Spot", "Desserts",         "$",    "Brooklyn dessert shop. Excellent soft serve and creative sundaes."),
        ("Nathan's Famous",     "American",         "$",    "Legendary Coney Island hot dogs since 1916. A NYC bucket-list bite.", "sfp"),
        ("Di Fara Pizza",       "Pizza",            "$$",   "Dom DeMarco's one-man pizza operation since 1964. Worth the schlep to Midwood. Cash only, long waits.", "sfp"),
        ("Totonno's",           "Pizza",            "$$",   "Coney Island pizza pioneer since 1924. Coal-fired, thin-crust, perfect. One of NYC's oldest.", "sfp"),
        ("Jade Island",         "Chinese Polynesian","$$",  "Staten Island tiki-Chinese time capsule. Worth the ferry trip for the novelty alone."),
        ("New Asha",            "Sri Lankan",       "$",    "Authentic Sri Lankan home cooking on Staten Island. The rice and curry plate is exceptional."),
        ("Joe & Pat's NYC",     "Pizza",            "$",    "Staten Island pizza legend since 1960. Thin-crust, simple, perfect."),
    ],
    "Queens": [
        ("Birria-Landia",       "Mexican",          "$",    "Jackson Heights birria specialists. The consommé-dipped quesabirria tacos are addictive."),
        ("Los Burritos Juarez", "Mexican",          "$",    "Authentic burritos in Jackson Heights. Massive, cheap, delicious."),
        ("Ruta Oaxaca",         "Mexican",          "$",    "Jackson Heights Oaxacan. Outstanding tlayudas and mole."),
        ("Los Dos Hermanos",    "Mexican",          "$",    "No-frills Queens taqueria. Excellent tacos and horchata."),
        ("El Patron Mexican Grill","Mexican",       "$",    "Solid neighbourhood Mexican in Queens. Great for an authentic, affordable meal."),
        ("Ganesh Temple Canteen","South Indian",    "$",    "Temple cafeteria in Flushing serving transcendent South Indian food — dosas, chutneys, sambar. Open to all. Phil's favourite NYC meal.", "sfp"),
    ],
}

CUISINE_COLORS = {
    "American":         "#e8f4fd",
    "Italian":          "#fff3e0",
    "Mexican":          "#e8fdf5",
    "French":           "#f0f4ff",
    "Korean":           "#fce4ec",
    "Japanese":         "#fdf4ff",
    "Chinese":          "#fffde7",
    "Indian":           "#fff8e1",
    "Mediterranean":    "#e8fdf5",
    "Pizza":            "#fff3e0",
    "Seafood":          "#e3f2fd",
    "Bar":              "#f3e5f5",
    "Cocktail Bar":     "#f3e5f5",
    "Wine Bar":         "#f3e5f5",
    "Rooftop Bar":      "#f3e5f5",
    "Bakery":           "#fce4ec",
    "Desserts":         "#fce4ec",
    "Vegan":            "#e8f5e9",
    "Vegan Mexican":    "#e8f5e9",
    "Vegetarian":       "#e8f5e9",
    "Lebanese":         "#fff3e0",
    "Greek":            "#e8f4fd",
    "Thai":             "#e8fdf5",
    "Vietnamese":       "#e8fdf5",
    "Peruvian":         "#e8fdf5",
    "Caribbean":        "#fff8e1",
    "West African":     "#fff8e1",
    "Pakistani":        "#fff8e1",
    "Ramen":            "#fffde7",
    "Jewish Deli":      "#f5f5f5",
    "Food Hall":        "#f5f5f5",
    "Café":             "#f5f5f5",
    "Entertainment":    "#ede7f6",
    "Deli":             "#f5f5f5",
}
